### ISSUE TITLE
Correct function in how-to slideshow

### ISSUE THREAD

**Issue by eligence** [mboynes/wcpdx-rewrite-recipes#1]
Thanks for this rewrite. A correction:

change `array_unshift` to `array_pop` on line 4

http://mboynes.github.io/wcpdx-rewrite-recipes/#/1/2

**Comment by mboynes** [comment]
I think for most cases, it makes sense to take the _first_ item in the array rather than the last. However, it entirely depends on the situation. How I wrote it isn't wrong, and neither is using `array_pop()`. I'm going to leave it as-is since there's no discernible advantage to updating it, but thanks for the suggestion all the same!

**Comment by eligence** [comment]
Using the first item does make more sense. However, if you keep the code as is, using `array_unshift` then you are not showing the correct solution and introducing a bug as it doesn't produce the desired effect. I think you would prefer using `array_shift` as this give you the behavior you are expecting and most likely meant in the first place.

`array_unshift` - Prepend one or more elements to the beginning of an array
http://php.net/manual/en/function.array-unshift.php 

`array_shift`- Shift an element off the beginning of array and return it
http://php.net/manual/en/function.array-shift.php

**Comment by mboynes** [comment]
🤦‍♂️ great catch, thanks! Funny, I clearly fixed that in [the working example code](https://github.com/mboynes/wcpdx-rewrite-recipes/blob/6d26f7e589495601524b298abec6f891dbe2c619/recipes/recipe-1.php#L41) but I guess it never made it back to the slides. I fixed them and ended up using `array_pop()` to be consistent with the sample code. Thanks again!
